<?php

namespace Database\Seeders;

use App\Models\Kota;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class KotaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $kotas = [
            ['nama' => 'Kabupaten Bangkalan',],
            ['nama' => 'Kabupaten Bangkalan',],
            ['nama' => 'Kabupaten Banyuwangi'],
            ['nama' => 'Kabupaten Blitar',],
            ['nama' => 'Kabupaten Bojonegoro',],
            ['nama' => 'Kabupaten Bondowoso',],
            ['nama' => 'Kabupaten Gresik',],
            ['nama' => 'Kabupaten Jembe',],
            ['nama' => 'Kabupaten Jombang',],
            ['nama' => 'Kabupaten Kediri',],
            ['nama' => 'Kabupaten Lamongan',],
            ['nama' => 'Kabupaten Lumajang',],
            ['nama' => 'Kabupaten Madiun',],
            ['nama' => 'Kabupaten Magetan',],
            ['nama' => 'Kabupaten Malang',],
            ['nama' => 'Kabupaten Mojokerto',],
            ['nama' => 'Kabupaten Nganjuk',],
            ['nama' => 'Kabupaten Ngawi',],
            ['nama' => 'Kabupaten Pacitan',],
            ['nama' => 'Kabupaten Pamekasan',],
            ['nama' => 'Kabupaten Pasuruan',],
            ['nama' => 'Kabupaten Ponorogo',],
            ['nama' => 'Kabupaten Probolinggo',],
            ['nama' => 'Kabupaten Sampang',],
            ['nama' => 'Kabupaten Sidoarjo',],
            ['nama' => 'Kabupaten Situbondo',],
            ['nama' => 'Kabupaten Sumenep',],
            ['nama' => 'Kabupaten Trenggalek',],
            ['nama' => 'Kabupaten Tuban',],
            ['nama' => 'Kabupaten Tulungagun',],
            ['nama' => 'Kota Batu',],
            ['nama' => 'Kota Blitar',],
            ['nama' => 'Kota Kediri',],
            ['nama' => 'Kota Madiun',],
            ['nama' => 'Kota Malang',],
            ['nama' => 'Kota Mojokert',],
            ['nama' => 'Kota Pasuruan',],
            ['nama' => 'Kota Probolinggo',],
            ['nama' => 'Kota Surabaya',],
            ['nama' => 'Kabupaten Banjarnegara',],
            ['nama' => 'Kabupaten Banyumas',],
            ['nama' => 'Kabupaten Batang',],
            ['nama' => 'Kabupaten Blora',],
            ['nama' => 'Kabupaten Boyolali',],
            ['nama' => 'Kabupaten Brebes',],
            ['nama' => 'Kabupaten Cilacap',],
            ['nama' => 'Kabupaten Demak',],
            ['nama' => 'Kabupaten Grobogan',],
            ['nama' => 'Kabupaten Jepara',],
            ['nama' => 'Kabupaten Karanganyar',],
            ['nama' => 'Kabupaten Kebumen',],
            ['nama' => 'Kabupaten Kendal',],
            ['nama' => 'Kabupaten Klaten',],
            ['nama' => 'Kabupaten Kudus',],
            ['nama' => 'Kabupaten Magelang',],
            ['nama' => 'Kabupaten Pati',],
            ['nama' => 'Kabupaten Pekalonga',],
            ['nama' => 'Kabupaten Pemalang',],
            ['nama' => 'Kabupaten Purbalingga',],
            ['nama' => 'Kabupaten Purworejo',],
            ['nama' => 'Kabupaten Remban',],
            ['nama' => 'Kabupaten Semarang',],
            ['nama' => 'Kabupaten Sragen',],
            ['nama' => 'Kabupaten Sukoharjo',],
            ['nama' => 'Kabupaten Tegal',],
            ['nama' => 'Kabupaten Temanggu',],
            ['nama' => 'Kabupaten Wonogiri',],
            ['nama' => 'Kabupaten Wonosobo',],
            ['nama' => 'Kota Magelang',],
            ['nama' => 'Kota Pekalongan',],
            ['nama' => 'Kota Salatiga',],
            ['nama' => 'Kota Semarang',],
            ['nama' => 'Kota Surakarta',],
            ['nama' => 'Kota Tegal',],
            ['nama' => 'Kabupaten Bandung',],
            ['nama' => 'Kabupaten Bandung Barat',],
            ['nama' => 'Kabupaten Bekasi',],
            ['nama' => 'Kabupaten Bogor',],
            ['nama' => 'Kabupaten Ciamis',],
            ['nama' => 'Kabupaten Cianjur',],
            ['nama' => 'Kabupaten Cirebon',],
            ['nama' => 'Kabupaten Garut',],
            ['nama' => 'Kabupaten Indramayu',],
            ['nama' => 'Kabupaten Karawang',],
            ['nama' => 'Kabupaten Kuningan',],
            ['nama' => 'Kabupaten Majalengka',],
            ['nama' => 'Kabupaten Pangandaran',],
            ['nama' => 'Kabupaten Purwakarta',],
            ['nama' => 'Kabupaten Subang',],
            ['nama' => 'Kabupaten Sukabumi',],
            ['nama' => 'Kabupaten Sumedang',],
            ['nama' => 'Kabupaten Tasikmalaya',],
            ['nama' => 'Kota Bandung',],
            ['nama' => 'Kota Banjar',],
            ['nama' => 'Kota Bekasi',],
            ['nama' => 'Kota Bogor',],
            ['nama' => 'Kota Cimahi',],
            ['nama' => 'Kota Cirebon',],
            ['nama' => 'Kota Depok',],
            ['nama' => 'Kota Sukabumi',],
            ['nama' => 'Kota Tasikmalaya',],
            ['nama' => 'Kabupaten Bantul',],
            ['nama' => 'Kabupaten Gunungkidul',],
            ['nama' => 'Kabupaten Kulon Prog',],
            ['nama' => 'Kabupaten Sleman',],
            ['nama' => 'Kota Yogyakarta',],
            ['nama' => 'Kabupaten Lebak',],
            ['nama' => 'Kabupaten Pandeglang',],
            ['nama' => 'Kabupaten Serang',],
            ['nama' => 'Kabupaten Tangerang',],
            ['nama' => 'Kota Cilegon',],
            ['nama' => 'Kota Serang',],
            ['nama' => 'Kota Tangerang',],
            ['nama' => 'Kota Tangerang Selatan',],
            ['nama' => 'Kabupaten  Kepulauan Seribu',],
            ['nama' => 'Kota Jakarta Barat',],
            ['nama' => 'Kota Jakarta Pusat',],
            ['nama' => 'Kota Jakarta Selatan',],
            ['nama' => 'Kota Jakarta Timur',],
            ['nama' => 'Kota Jakarta Utara',],
        ];
        Kota::insert($kotas);
    }
}
